### ISSUE TITLE
Don't use Slack tokens in URL

### ISSUE THREAD

**Issue by kayex** [adsa95/sirius-api#8]
We should probably not use Slack tokens as URL identifiers, as they are sensitive pieces of data that can accidentally be captured in request/routing logs etc.

Suggestions for alternate IDs to use?

The SHA256 hash of `TeamID` and `UserID` is very convenient for the `sirius` service since it can be fetched at any time using a Slack token only.

I can take responsibility for implementing this change (on both sides).

**Comment by adsa95** [comment]
A SHA256 hash sounds like a good solution. Don't forget that this must be provided in the response when saving a new config as API clients don't have access to the Slack API to get this themselves. Go for it!

**Comment by kayex** [comment]
Good point! I'll make sure it's included.

**Comment by kayex** [comment]
Hmm, since the `TeamID` and `UserID` are unlikely to change, we must assume that the SHA-256 sum will be the same for all tokens generated by a user.

This will generate a notification flow that doesn't feel intuitive at all. For example, if an existing user with the ID hash `6cea57` switches their token, the following notifications will be published:

```
DELETE 6cea57
NEW 6cea57
```

To the uninitiated, this might be tempting to refactor into a single `UPDATE` notification, since the ID hash is the same for both the `DELETE` and `UPDATE` messages. However, a token switch must always be communicated by dropping the old config (using `DELETE`) and registering the user anew (using `NEW`). This is currently made obvious by the fact that the call to `DELETE` includes the old token while the call to `NEW` includes the new one.

Perhaps we should include the token (or part of the token) in the input to the SHA-256? This is an easy way to guarantee that every combination of `Token`/`TeamID`/`UserID` generates a unique hash ID.

**Comment by adsa95** [comment]
Client side the best thing would probably be to make a true Slack app and use Slack Oauth login, then requesting current configurations could be `/configs/me`  or something similar to that.

**Comment by kayex** [comment]
Probably. There still needs to be a unique client ID sent via MQTT, though.
